// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PremierAthletics.Models;

namespace hellosignmvc.Migrations
{
    [DbContext(typeof(PremierAthleticsContext))]
    partial class PremierAthleticsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.6");

            modelBuilder.Entity("PremierAthletics.Models.Athlete", b =>
                {
                    b.Property<string>("AthleteId")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("Birthday")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FirstName")
                        .HasColumnType("longtext");

                    b.Property<string>("LastName")
                        .HasColumnType("longtext");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("AthleteId");

                    b.ToTable("Athletes");
                });

            modelBuilder.Entity("PremierAthletics.Models.AthleteTeam", b =>
                {
                    b.Property<int>("AthleteTeamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AthleteId")
                        .HasColumnType("int");

                    b.Property<string>("AthleteId1")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.Property<string>("TeamId1")
                        .HasColumnType("varchar(255)");

                    b.HasKey("AthleteTeamId");

                    b.HasIndex("AthleteId1");

                    b.HasIndex("TeamId1");

                    b.ToTable("AthleteTeam");
                });

            modelBuilder.Entity("PremierAthletics.Models.SignatureRequest", b =>
                {
                    b.Property<string>("SignatureRequestId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("SignatureRequestId");

                    b.ToTable("SignatureRequests");
                });

            modelBuilder.Entity("PremierAthletics.Models.SignatureRequestTeam", b =>
                {
                    b.Property<int>("SignatureRequestTeamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("SignatureRequestId")
                        .HasColumnType("int");

                    b.Property<string>("SignatureRequestId1")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.Property<string>("TeamId1")
                        .HasColumnType("varchar(255)");

                    b.HasKey("SignatureRequestTeamId");

                    b.HasIndex("SignatureRequestId1");

                    b.HasIndex("TeamId1");

                    b.ToTable("SignatureRequestTeam");
                });

            modelBuilder.Entity("PremierAthletics.Models.Team", b =>
                {
                    b.Property<string>("TeamId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Sport")
                        .HasColumnType("longtext");

                    b.Property<string>("TeamName")
                        .HasColumnType("longtext");

                    b.HasKey("TeamId");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("PremierAthletics.Models.AthleteTeam", b =>
                {
                    b.HasOne("PremierAthletics.Models.Athlete", "Athlete")
                        .WithMany("Teams")
                        .HasForeignKey("AthleteId1");

                    b.HasOne("PremierAthletics.Models.Team", "Team")
                        .WithMany("Athletes")
                        .HasForeignKey("TeamId1");

                    b.Navigation("Athlete");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("PremierAthletics.Models.SignatureRequestTeam", b =>
                {
                    b.HasOne("PremierAthletics.Models.SignatureRequest", "SignatureRequest")
                        .WithMany("Teams")
                        .HasForeignKey("SignatureRequestId1");

                    b.HasOne("PremierAthletics.Models.Team", "Team")
                        .WithMany("SignatureRequests")
                        .HasForeignKey("TeamId1");

                    b.Navigation("SignatureRequest");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("PremierAthletics.Models.Athlete", b =>
                {
                    b.Navigation("Teams");
                });

            modelBuilder.Entity("PremierAthletics.Models.SignatureRequest", b =>
                {
                    b.Navigation("Teams");
                });

            modelBuilder.Entity("PremierAthletics.Models.Team", b =>
                {
                    b.Navigation("Athletes");

                    b.Navigation("SignatureRequests");
                });
#pragma warning restore 612, 618
        }
    }
}
